name: dio_proxy_plugin
description: a proxy for Dio . dio_proxy  interceptor can help us debug network traffic .
version: 2.0.1
homepage: 'https://github.com/csdntm/dio_proxy_plugin'
environment:
  sdk: '>=2.7.0 <4.0.0'
  flutter: '>=2.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: '>=2.1.9'
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
  pretty_dio_logger: any
flutter:
  plugin:
    platforms:
      android:
        package: net.csdn.dio_proxy_plugin
        pluginClass: DioProxyPlugin
      ios:
        pluginClass: DioProxyPlugin
