name: dio_proxy_plugin
description: a proxy for Dio . dio_proxy  interceptor can help us debug network traffic .
version: 2.0.3
homepage: 'https://github.com/csdntm/dio_proxy_plugin'
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: '>=4.0.0'
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: net.csdn.dio_proxy_plugin
        pluginClass: DioProxyPlugin
      ios:
        pluginClass: DioProxyPlugin
